# numpy

In [1]:
import numpy as np


In [3]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)



In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape


(5,)

In [16]:
my_list1 = [1,2,3,4,5]
my_list2 = [3,6,3,4,5]
my_list3 = [6,3,3,4,5]
arr1 =np.array([my_list1,my_list2,my_list3])

In [17]:
arr1


array([[1, 2, 3, 4, 5],
       [3, 6, 3, 4, 5],
       [6, 3, 3, 4, 5]])

In [19]:
arr1.shape


(3, 5)

In [21]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [6, 3, 4],
       [5, 6, 3],
       [3, 4, 5]])

# indexing

In [22]:
arr = np.array([1,2,3,4,5,6,7])
arr[3]

4

In [23]:
arr1


array([[1, 2, 3, 4, 5],
       [3, 6, 3, 4, 5],
       [6, 3, 3, 4, 5]])

In [25]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [3, 6, 3, 4, 5],
       [6, 3, 3, 4, 5]])

In [26]:
arr1[0:2,:]

array([[1, 2, 3, 4, 5],
       [3, 6, 3, 4, 5]])

In [27]:
arr1[0:2,0:2]


array([[1, 2],
       [3, 6]])

In [30]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [3, 6, 3, 4, 5],
       [6, 3, 3, 4, 5]])

In [33]:
arr1[1:,2:4]


array([[3, 4],
       [3, 4]])

In [37]:
arr2= np.arange(0,12,step =2)

In [43]:
arr2[3:]=100
arr2

array([  0,   2,   4, 100, 100, 100])

In [45]:
arr3 =arr2.copy()


In [46]:
arr3

array([  0,   2,   4, 100, 100, 100])